### ISSUE TITLE
Add fan-menu

### ISSUE THREAD

**Issue by zapletnev** [younatics/MotionBook#3]
Thanks for creating MotionBook!

What should I do to add fan-menu in your list? https://github.com/exyte/fan-menu
Fan-menu bases on Macaw from your list.

**Comment by younatics** [comment]
Great Library! 
This is my mistake, I update now about [CONTRIBUTING.md] (https://github.com/younatics/MotionBook/blob/master/CONTRIBUTING.md)

Could you follow this guideline and pull request me again? Thanks!

**Comment by zapletnev** [comment]
@younatics thanks! Unfortunately, fan-menu doesn't have 200 stars yet. ⭐️

**Comment by younatics** [comment]
After that, I will import sample and your library too! 
Thank you for your great library :)
