### ISSUE TITLE
Logo Project Proposal

### ISSUE THREAD

**Issue by debpedrano** [younatics/MotionBook#7]
Good day Project Owner, I am offering you a new logo for the project for free. If it would be okay to you

**Comment by younatics** [comment]
Hello @debpedrano ,
Sure! could you make PR or send me an email with logos? 
I will consider about it!
Thanks!

**Comment by debpedrano** [comment]
sorry for the late response, I was so busy this past few days. I will make the design now and ill comment it here as soon as I am done. Thank you ! @younatics

**Comment by debpedrano** [comment]
I do not know if the small " m " or the big " M  " fits right , if you have suggestion, please feel free to tell me. Thanks @younatics  !

![image](https://user-images.githubusercontent.com/40510200/43674645-0d8a16a2-980a-11e8-9271-5128564177b5.png)

**Comment by farmanp** [comment]
I neither own nor have a big involvement in the project, but I would say the skinnier M is more pleasing in an aesthetic sense - can you change the font to show what "MotionBook" would look like in a skinnier font?
